version: '2.1'

services:
  server:
    command: "npm run start:dev"
    image: nestjs:latest
    environment:
      VIRTUAL_HOST: api.local
    expose:
      - 3000
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app

networks:
  default:
    external:
      name: enfrausa